# .github/workflows/convert-mod-to-flac.yml
name: Convert MOD to FLAC and Commit

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '変換対象のアーカイブファイルのダウンロード URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history を取得してコミットが可能に

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            p7zip-full \
            unzip \
            unar \
            ffmpeg

      - name: Download archive
        run: |
          echo "Downloading ${{ github.event.inputs.download_url }}..."
          curl -L --output archive "${{ github.event.inputs.download_url }}"

      - name: Extract archive
        run: |
          mkdir extracted
          case "${{ github.event.inputs.download_url##*. }}" in
            7z) 7z x -oextracted archive ;;
            zip) unzip archive -d extracted ;;
            lzh) unar -o extracted archive ;;
            raw)
              cp archive extracted/ ;;
            *)
              echo "Unsupported extension: ${${{ github.event.inputs.download_url##*. }}}"
              exit 1
              ;;
          esac

      - name: Find and convert MOD files to FLAC
        run: |
          mkdir -p flac_output
          find extracted -type f \( \
            -iname '*.mod' \
            -o -iname '*.s3m' \
            -o -iname '*.xm' \
            -o -iname '*.it' \
          \) | while read -r filepath; do
            filename=$(basename "$filepath")
            base="${filename%.*}"
            echo "Converting $filename → ${base}.flac"
            ffmpeg -y -i "$filepath" "flac_output/${base}.flac"
          done

      - name: Copy FLACs into repo
        run: |
          # 例えば output/flac 内に集約
          mkdir -p mods/flac
          cp flac_output/*.flac mods/flac/ || true

      - name: Configure Git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push FLAC files
        run: |
          git add mods/flac
          # 変更があればコミット
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add converted FLAC files from ${{ github.event.inputs.download_url }}"
            git push origin HEAD:${{ github.ref_name }}
          fi
        env:
          # GITHUB_TOKEN は自動で設定されるので特別な設定不要
          PINOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
